# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Wildcard
version:      0.09
version_from: lib/File/Wildcard.pm
installdirs:  site
requires:
    Module::Optional:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
